### ISSUE TITLE
Preview was not working till service was restarted

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/giveth-1-preview#2]
Suddenly I noticed the preview of this project is not working on Telegram and What's App. I restarted the service and tested it again in Discord and it became OK.

https://beta.giveth.io/campaigns/5b39d45e14cec916d00dab20/milestones/6015da7f76ce7f1636ff6173

It's the server log
[giveth-preview-beta-out.log](https://github.com/Giveth/giveth-1-preview/files/5898869/giveth-preview-beta-out.log)

**Comment by aminlatifi** [comment]
![image](https://user-images.githubusercontent.com/5684607/106369932-d10e7180-636a-11eb-826b-a98248e14c3a.png)

**Comment by mdehghani** [comment]
I didn't find the problem yet. If it occurs again, please don't reset the server and let me know that the problem is occurred. @aminlatifi
